# Generated by Django 2.0.10 on 2019-01-30 05:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(max_length=1024)),
                ('m_time', models.DateTimeField(auto_now=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_unreviewed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['m_time'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=256, upload_to=login.models.img_directory_path)),
                ('result', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.IntegerField(default=1)),
                ('content', models.TextField(max_length=1024)),
                ('name', models.CharField(max_length=128)),
                ('details', models.TextField(max_length=1024)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('max_tagged_num', models.IntegerField(default=1)),
                ('is_closed', models.BooleanField(default=False)),
                ('credit', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Task')),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_credits', models.IntegerField(default=1000)),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
        migrations.AddField(
            model_name='taskuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='released_tasks', to='login.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(related_name='favorite_tasks', through='login.TaskUser', to='login.User'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Task'),
        ),
        migrations.AddField(
            model_name='label',
            name='sub_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.SubTask'),
        ),
        migrations.AddField(
            model_name='label',
            name='task_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.TaskUser'),
        ),
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.User'),
        ),
    ]
