# Generated by Django 2.0.5 on 2018-08-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['c_time']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
