# Generated by Django 2.0.5 on 2018-08-26 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20180818_0358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['c_time']},
        ),
        migrations.AddField(
            model_name='task',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.TextField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
    ]
