# Generated by Django 2.1.7 on 2019-04-17 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_auto_20190228_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.TextField(max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='label',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='label',
            name='is_unreviewed',
        ),
        migrations.RemoveField(
            model_name='label',
            name='redo',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='is_grabbed',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='num_label_reviewed',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='pre_user',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='redo',
        ),
        migrations.AddField(
            model_name='label',
            name='status',
            field=models.CharField(default='untagged', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='num_worker',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='num_label_rejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='status',
            field=models.CharField(default='doing', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskuser',
            name='num_label_unreviewed',
            field=models.IntegerField(default=-1),
        ),
    ]
