# Generated by Django 2.1.7 on 2019-04-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_auto_20190417_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_label_accepted',
            field=models.IntegerField(default=0),
        ),
    ]
