# Generated by Django 2.1.7 on 2019-04-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_auto_20190417_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='has_grabbed',
            field=models.BooleanField(default=False),
        ),
    ]
